<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('currencies')->count() > 0) { return; }

        $now = now();
        DB::table('currencies')->insert([
            ['uuid' => (string) Str::uuid(), 'country_id' => 1, 'currency' => 'AFN', 'currency_name' => 'Afghan afghani', 'currency_symbol' => '؋', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 2, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 3, 'currency' => 'ALL', 'currency_name' => 'Albanian lek', 'currency_symbol' => 'Lek', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 4, 'currency' => 'DZD', 'currency_name' => 'Algerian dinar', 'currency_symbol' => 'دج', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 5, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 6, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 7, 'currency' => 'AOA', 'currency_name' => 'Angolan kwanza', 'currency_symbol' => 'Kz', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 8, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 9, 'currency' => 'AAD', 'currency_name' => 'Antarctican dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 10, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 11, 'currency' => 'ARS', 'currency_name' => 'Argentine peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 12, 'currency' => 'AMD', 'currency_name' => 'Armenian dram', 'currency_symbol' => '֏', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 13, 'currency' => 'AWG', 'currency_name' => 'Aruban florin', 'currency_symbol' => 'ƒ', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 14, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 15, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 16, 'currency' => 'AZN', 'currency_name' => 'Azerbaijani manat', 'currency_symbol' => 'm', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 17, 'currency' => 'BSD', 'currency_name' => 'Bahamian dollar', 'currency_symbol' => 'B$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 18, 'currency' => 'BHD', 'currency_name' => 'Bahraini dinar', 'currency_symbol' => '.د.ب', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 19, 'currency' => 'BDT', 'currency_name' => 'Bangladeshi taka', 'currency_symbol' => '৳', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 20, 'currency' => 'BBD', 'currency_name' => 'Barbadian dollar', 'currency_symbol' => 'Bds$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 21, 'currency' => 'BYN', 'currency_name' => 'Belarusian ruble', 'currency_symbol' => 'Br', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 22, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 23, 'currency' => 'BZD', 'currency_name' => 'Belize dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 24, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 25, 'currency' => 'BMD', 'currency_name' => 'Bermudian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 26, 'currency' => 'BTN', 'currency_name' => 'Bhutanese ngultrum', 'currency_symbol' => 'Nu.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 27, 'currency' => 'BOB', 'currency_name' => 'Bolivian boliviano', 'currency_symbol' => 'Bs.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 28, 'currency' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina convertible mark', 'currency_symbol' => 'KM', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 29, 'currency' => 'BWP', 'currency_name' => 'Botswana pula', 'currency_symbol' => 'P', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 30, 'currency' => 'NOK', 'currency_name' => 'Norwegian krone', 'currency_symbol' => 'ko', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 31, 'currency' => 'BRL', 'currency_name' => 'Brazilian real', 'currency_symbol' => 'R$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 32, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 33, 'currency' => 'BND', 'currency_name' => 'Brunei dollar', 'currency_symbol' => 'B$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 34, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 35, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 36, 'currency' => 'BIF', 'currency_name' => 'Burundian franc', 'currency_symbol' => 'FBu', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 37, 'currency' => 'KHR', 'currency_name' => 'Cambodian riel', 'currency_symbol' => 'KHR', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 38, 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 39, 'currency' => 'CAD', 'currency_name' => 'Canadian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 40, 'currency' => 'CVE', 'currency_name' => 'Cape Verdean escudo', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 41, 'currency' => 'KYD', 'currency_name' => 'Cayman Islands dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 42, 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 43, 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 44, 'currency' => 'CLP', 'currency_name' => 'Chilean peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 45, 'currency' => 'CNY', 'currency_name' => 'Chinese yuan', 'currency_symbol' => '¥', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 46, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 47, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 48, 'currency' => 'COP', 'currency_name' => 'Colombian peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 49, 'currency' => 'KMF', 'currency_name' => 'Comorian franc', 'currency_symbol' => 'CF', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 50, 'currency' => 'CDF', 'currency_name' => 'Congolese Franc', 'currency_symbol' => 'FC', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 51, 'currency' => 'CDF', 'currency_name' => 'Congolese Franc', 'currency_symbol' => 'FC', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 52, 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 53, 'currency' => 'CRC', 'currency_name' => 'Costa Rican colón', 'currency_symbol' => '₡', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 54, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 55, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 56, 'currency' => 'CUP', 'currency_name' => 'Cuban peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 57, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 58, 'currency' => 'CZK', 'currency_name' => 'Czech koruna', 'currency_symbol' => 'Kč', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 59, 'currency' => 'DKK', 'currency_name' => 'Danish krone', 'currency_symbol' => 'Kr.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 60, 'currency' => 'DJF', 'currency_name' => 'Djiboutian franc', 'currency_symbol' => 'Fdj', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ]);

        DB::table('currencies')->insert([
            ['uuid' => (string) Str::uuid(), 'country_id' => 61, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 62, 'currency' => 'DOP', 'currency_name' => 'Dominican peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 63, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 64, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 65, 'currency' => 'EGP', 'currency_name' => 'Egyptian pound', 'currency_symbol' => 'ج.م', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 66, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 67, 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 68, 'currency' => 'ERN', 'currency_name' => 'Eritrean nakfa', 'currency_symbol' => 'Nfk', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 69, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 70, 'currency' => 'ETB', 'currency_name' => 'Ethiopian birr', 'currency_symbol' => 'Nkf', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 71, 'currency' => 'FKP', 'currency_name' => 'Falkland Islands pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 72, 'currency' => 'DKK', 'currency_name' => 'Danish krone', 'currency_symbol' => 'Kr.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 73, 'currency' => 'FJD', 'currency_name' => 'Fijian dollar', 'currency_symbol' => 'FJ$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 74, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 75, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 76, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 77, 'currency' => 'XPF', 'currency_name' => 'CFP franc', 'currency_symbol' => '₣', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 78, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 79, 'currency' => 'XAF', 'currency_name' => 'Central African CFA franc', 'currency_symbol' => 'FCFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 80, 'currency' => 'GMD', 'currency_name' => 'Gambian dalasi', 'currency_symbol' => 'D', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 81, 'currency' => 'GEL', 'currency_name' => 'Georgian lari', 'currency_symbol' => 'ლ', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 82, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 83, 'currency' => 'GHS', 'currency_name' => 'Ghanaian cedi', 'currency_symbol' => 'GH₵', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 84, 'currency' => 'GIP', 'currency_name' => 'Gibraltar pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 85, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 86, 'currency' => 'DKK', 'currency_name' => 'Danish krone', 'currency_symbol' => 'Kr.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 87, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 88, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 89, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 90, 'currency' => 'GTQ', 'currency_name' => 'Guatemalan quetzal', 'currency_symbol' => 'Q', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 91, 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 92, 'currency' => 'GNF', 'currency_name' => 'Guinean franc', 'currency_symbol' => 'FG', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 93, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 94, 'currency' => 'GYD', 'currency_name' => 'Guyanese dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 95, 'currency' => 'HTG', 'currency_name' => 'Haitian gourde', 'currency_symbol' => 'G', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 96, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 97, 'currency' => 'HNL', 'currency_name' => 'Honduran lempira', 'currency_symbol' => 'L', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 98, 'currency' => 'HKD', 'currency_name' => 'Hong Kong dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 99, 'currency' => 'HUF', 'currency_name' => 'Hungarian forint', 'currency_symbol' => 'Ft', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 100, 'currency' => 'ISK', 'currency_name' => 'Icelandic króna', 'currency_symbol' => 'ko', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 101, 'currency' => 'INR', 'currency_name' => 'Indian rupee', 'currency_symbol' => '₹', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 102, 'currency' => 'IDR', 'currency_name' => 'Indonesian rupiah', 'currency_symbol' => 'Rp', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 103, 'currency' => 'IRR', 'currency_name' => 'Iranian rial', 'currency_symbol' => '﷼', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 104, 'currency' => 'IQD', 'currency_name' => 'Iraqi dinar', 'currency_symbol' => 'د.ع', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 105, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 106, 'currency' => 'ILS', 'currency_name' => 'Israeli new shekel', 'currency_symbol' => '₪', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 107, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 108, 'currency' => 'JMD', 'currency_name' => 'Jamaican dollar', 'currency_symbol' => 'J$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 109, 'currency' => 'JPY', 'currency_name' => 'Japanese yen', 'currency_symbol' => '¥', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 110, 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 111, 'currency' => 'JOD', 'currency_name' => 'Jordanian dinar', 'currency_symbol' => 'ا.د', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 112, 'currency' => 'KZT', 'currency_name' => 'Kazakhstani tenge', 'currency_symbol' => 'лв', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 113, 'currency' => 'KES', 'currency_name' => 'Kenyan shilling', 'currency_symbol' => 'KSh', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 114, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 115, 'currency' => 'KPW', 'currency_name' => 'North Korean Won', 'currency_symbol' => '₩', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 116, 'currency' => 'KRW', 'currency_name' => 'Won', 'currency_symbol' => '₩', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 117, 'currency' => 'KWD', 'currency_name' => 'Kuwaiti dinar', 'currency_symbol' => 'ك.د', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 118, 'currency' => 'KGS', 'currency_name' => 'Kyrgyzstani som', 'currency_symbol' => 'лв', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 119, 'currency' => 'LAK', 'currency_name' => 'Lao kip', 'currency_symbol' => '₭', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 120, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ]);

        DB::table('currencies')->insert([
            ['uuid' => (string) Str::uuid(), 'country_id' => 121, 'currency' => 'LBP', 'currency_name' => 'Lebanese pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 122, 'currency' => 'LSL', 'currency_name' => 'Lesotho loti', 'currency_symbol' => 'L', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 123, 'currency' => 'LRD', 'currency_name' => 'Liberian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 124, 'currency' => 'LYD', 'currency_name' => 'Libyan dinar', 'currency_symbol' => 'د.ل', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 125, 'currency' => 'CHF', 'currency_name' => 'Swiss franc', 'currency_symbol' => 'CHf', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 126, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 127, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 128, 'currency' => 'MOP', 'currency_name' => 'Macanese pataca', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 129, 'currency' => 'MKD', 'currency_name' => 'Denar', 'currency_symbol' => 'ден', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 130, 'currency' => 'MGA', 'currency_name' => 'Malagasy ariary', 'currency_symbol' => 'Ar', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 131, 'currency' => 'MWK', 'currency_name' => 'Malawian kwacha', 'currency_symbol' => 'MK', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 132, 'currency' => 'MYR', 'currency_name' => 'Malaysian ringgit', 'currency_symbol' => 'RM', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 133, 'currency' => 'MVR', 'currency_name' => 'Maldivian rufiyaa', 'currency_symbol' => 'Rf', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 134, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 135, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 136, 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 137, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 138, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 139, 'currency' => 'MRU', 'currency_name' => 'Mauritanian ouguiya', 'currency_symbol' => 'UM', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 140, 'currency' => 'MUR', 'currency_name' => 'Mauritian rupee', 'currency_symbol' => '₨', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 141, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 142, 'currency' => 'MXN', 'currency_name' => 'Mexican peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 143, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 144, 'currency' => 'MDL', 'currency_name' => 'Moldovan leu', 'currency_symbol' => 'L', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 145, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 146, 'currency' => 'MNT', 'currency_name' => 'Mongolian tögrög', 'currency_symbol' => '₮', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 147, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 148, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 149, 'currency' => 'MAD', 'currency_name' => 'Moroccan dirham', 'currency_symbol' => 'DH', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 150, 'currency' => 'MZN', 'currency_name' => 'Mozambican metical', 'currency_symbol' => 'MT', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 151, 'currency' => 'MMK', 'currency_name' => 'Burmese kyat', 'currency_symbol' => 'K', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 152, 'currency' => 'NAD', 'currency_name' => 'Namibian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 153, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 154, 'currency' => 'NPR', 'currency_name' => 'Nepalese rupee', 'currency_symbol' => '₨', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 155, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 156, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 157, 'currency' => 'XPF', 'currency_name' => 'CFP franc', 'currency_symbol' => '₣', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 158, 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 159, 'currency' => 'NIO', 'currency_name' => 'Nicaraguan córdoba', 'currency_symbol' => 'C$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 160, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 161, 'currency' => 'NGN', 'currency_name' => 'Nigerian naira', 'currency_symbol' => '₦', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 162, 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 163, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 164, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 165, 'currency' => 'NOK', 'currency_name' => 'Norwegian krone', 'currency_symbol' => 'ko', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 166, 'currency' => 'OMR', 'currency_name' => 'Omani rial', 'currency_symbol' => '.ع.ر', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 167, 'currency' => 'PKR', 'currency_name' => 'Pakistani rupee', 'currency_symbol' => '₨', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 168, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 169, 'currency' => 'ILS', 'currency_name' => 'Israeli new shekel', 'currency_symbol' => '₪', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 170, 'currency' => 'PAB', 'currency_name' => 'Panamanian balboa', 'currency_symbol' => 'B/.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 171, 'currency' => 'PGK', 'currency_name' => 'Papua New Guinean kina', 'currency_symbol' => 'K', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 172, 'currency' => 'PYG', 'currency_name' => 'Paraguayan guarani', 'currency_symbol' => '₲', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 173, 'currency' => 'PEN', 'currency_name' => 'Peruvian sol', 'currency_symbol' => 'S/.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 174, 'currency' => 'PHP', 'currency_name' => 'Philippine peso', 'currency_symbol' => '₱', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 175, 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 176, 'currency' => 'PLN', 'currency_name' => 'Polish złoty', 'currency_symbol' => 'zł', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 177, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 178, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 179, 'currency' => 'QAR', 'currency_name' => 'Qatari riyal', 'currency_symbol' => 'ق.ر', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 180, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ]);

        DB::table('currencies')->insert([
            ['uuid' => (string) Str::uuid(), 'country_id' => 181, 'currency' => 'RON', 'currency_name' => 'Romanian leu', 'currency_symbol' => 'lei', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 182, 'currency' => 'RUB', 'currency_name' => 'Russian ruble', 'currency_symbol' => '₽', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 183, 'currency' => 'RWF', 'currency_name' => 'Rwandan franc', 'currency_symbol' => 'FRw', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 184, 'currency' => 'SHP', 'currency_name' => 'Saint Helena pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 185, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 186, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 187, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 188, 'currency' => 'XCD', 'currency_name' => 'Eastern Caribbean dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 189, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 190, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 191, 'currency' => 'WST', 'currency_name' => 'Samoan tālā', 'currency_symbol' => 'SAT', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 192, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 193, 'currency' => 'STN', 'currency_name' => 'Dobra', 'currency_symbol' => 'Db', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 194, 'currency' => 'SAR', 'currency_name' => 'Saudi riyal', 'currency_symbol' => '﷼', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 195, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 196, 'currency' => 'RSD', 'currency_name' => 'Serbian dinar', 'currency_symbol' => 'din', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 197, 'currency' => 'SCR', 'currency_name' => 'Seychellois rupee', 'currency_symbol' => 'SRe', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 198, 'currency' => 'SLL', 'currency_name' => 'Sierra Leonean leone', 'currency_symbol' => 'Le', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 199, 'currency' => 'SGD', 'currency_name' => 'Singapore dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 200, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 201, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 202, 'currency' => 'SBD', 'currency_name' => 'Solomon Islands dollar', 'currency_symbol' => 'Si$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 203, 'currency' => 'SOS', 'currency_name' => 'Somali shilling', 'currency_symbol' => 'Sh.so.', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 204, 'currency' => 'ZAR', 'currency_name' => 'South African rand', 'currency_symbol' => 'R', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 205, 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 206, 'currency' => 'SSP', 'currency_name' => 'South Sudanese pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 207, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 208, 'currency' => 'LKR', 'currency_name' => 'Sri Lankan rupee', 'currency_symbol' => 'Rs', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 209, 'currency' => 'SDG', 'currency_name' => 'Sudanese pound', 'currency_symbol' => '.س.ج', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 210, 'currency' => 'SRD', 'currency_name' => 'Surinamese dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 211, 'currency' => 'NOK', 'currency_name' => 'Norwegian krone', 'currency_symbol' => 'ko', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 212, 'currency' => 'SZL', 'currency_name' => 'Lilangeni', 'currency_symbol' => 'E', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 213, 'currency' => 'SEK', 'currency_name' => 'Swedish krona', 'currency_symbol' => 'ko', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 214, 'currency' => 'CHF', 'currency_name' => 'Swiss franc', 'currency_symbol' => 'CHf', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 215, 'currency' => 'SYP', 'currency_name' => 'Syrian pound', 'currency_symbol' => 'LS', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 216, 'currency' => 'TWD', 'currency_name' => 'New Taiwan dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 217, 'currency' => 'TJS', 'currency_name' => 'Tajikistani somoni', 'currency_symbol' => 'SM', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 218, 'currency' => 'TZS', 'currency_name' => 'Tanzanian shilling', 'currency_symbol' => 'TSh', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 219, 'currency' => 'THB', 'currency_name' => 'Thai baht', 'currency_symbol' => '฿', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 220, 'currency' => 'XOF', 'currency_name' => 'West African CFA franc', 'currency_symbol' => 'CFA', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 221, 'currency' => 'NZD', 'currency_name' => 'New Zealand dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 222, 'currency' => 'TOP', 'currency_name' => 'Tongan paʻanga', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 223, 'currency' => 'TTD', 'currency_name' => 'Trinidad and Tobago dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 224, 'currency' => 'TND', 'currency_name' => 'Tunisian dinar', 'currency_symbol' => 'ت.د', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 225, 'currency' => 'TRY', 'currency_name' => 'Turkish lira', 'currency_symbol' => '₺', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 226, 'currency' => 'TMT', 'currency_name' => 'Turkmenistan manat', 'currency_symbol' => 'T', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 227, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 228, 'currency' => 'AUD', 'currency_name' => 'Australian dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 229, 'currency' => 'UGX', 'currency_name' => 'Ugandan shilling', 'currency_symbol' => 'USh', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 230, 'currency' => 'UAH', 'currency_name' => 'Ukrainian hryvnia', 'currency_symbol' => '₴', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 231, 'currency' => 'AED', 'currency_name' => 'United Arab Emirates dirham', 'currency_symbol' => 'إ.د', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 232, 'currency' => 'GBP', 'currency_name' => 'British pound', 'currency_symbol' => '£', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 233, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 234, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 235, 'currency' => 'UYU', 'currency_name' => 'Uruguayan peso', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 236, 'currency' => 'UZS', 'currency_name' => 'Uzbekistani soʻm', 'currency_symbol' => 'лв', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 237, 'currency' => 'VUV', 'currency_name' => 'Vanuatu vatu', 'currency_symbol' => 'VT', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 238, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 239, 'currency' => 'VES', 'currency_name' => 'Bolívar', 'currency_symbol' => 'Bs', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 240, 'currency' => 'VND', 'currency_name' => 'Vietnamese đồng', 'currency_symbol' => '₫', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ]);

        DB::table('currencies')->insert([
            ['uuid' => (string) Str::uuid(), 'country_id' => 241, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 242, 'currency' => 'USD', 'currency_name' => 'United States dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 243, 'currency' => 'XPF', 'currency_name' => 'CFP franc', 'currency_symbol' => '₣', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 244, 'currency' => 'MAD', 'currency_name' => 'Moroccan dirham', 'currency_symbol' => 'DH', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 245, 'currency' => 'YER', 'currency_name' => 'Yemeni rial', 'currency_symbol' => '﷼', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 246, 'currency' => 'ZMW', 'currency_name' => 'Zambian kwacha', 'currency_symbol' => 'ZK', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 247, 'currency' => 'ZWL', 'currency_name' => 'Zimbabwe Dollar', 'currency_symbol' => '$', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 248, 'currency' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 249, 'currency' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder', 'currency_symbol' => 'ƒ', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
            ['uuid' => (string) Str::uuid(), 'country_id' => 250, 'currency' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder', 'currency_symbol' => 'ƒ', 'is_active' => true, 'created_at' => $now, 'updated_at' => $now],
        ]);

    }
}
