<?php

declare(strict_types=1);

namespace App\Mail;

use App\Models\User;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;

/**
 * PasswordResetMail — password reset link email.
 *
 * Used by User::sendPasswordResetNotification() to deliver a branded reset link.
 * The token is already generated by Laravel's Password broker.
 */
final class PasswordResetMail extends BaseMailable
{
    public function __construct(
        public readonly User   $user,
        public readonly string $token,
    ) {
        parent::__construct();
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: "Reset your {$this->appName()} password",
        );
    }

    public function content(): Content
    {
        $resetUrl = url(route('password.reset', [
            'token' => $this->token,
            'email' => $this->user->email,
        ], false));

        return new Content(
            view: 'emails.password-reset',
            with: [
                'user'      => $this->user,
                'resetUrl'  => $resetUrl,
                'appName'   => $this->appName(),
                'expiresIn' => config('auth.passwords.users.expire', 60),
            ],
        );
    }
}
